### ISSUE TITLE
Improve requirements.txt file parsing

### ISSUE THREAD

**Issue by symroe** [librariesio/librarian-parsers#109]
The current implementation of the requirements parser doesn't fully support the format as outlined here:

https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format

I noticed because [my project](https://libraries.io/github/DemocracyClub/WhoCanIVoteFor) is reported as having no dependancies, I think because I am using the `-r` format in my `requirements.txt` file to import other requirements files.

This is a fairly common patten in my experience, so I expect it would be worth supporting properly.

This looks like a good starting point for parsing requirements, but I've not tested to see if it supports `-r` in the files either:

https://github.com/davidfischer/requirements-parser

**Comment by andrew** [comment]
@symroe definitely needs improving but there are dependencies listed for you project at the moment, are you not seeing them? 

![screen shot 2017-01-06 at 3 34 37 pm](https://cloud.githubusercontent.com/assets/1060/21722712/b7a2e6be-d425-11e6-9f28-a1cebabc5d29.png)

**Comment by symroe** [comment]
What's the URL for that page? I'm looking at this, on https://libraries.io/github/DemocracyClub/WhoCanIVoteFor

![screen shot 2017-01-06 at 15 36 43](https://cloud.githubusercontent.com/assets/242329/21722777/efcbf8aa-d425-11e6-9a09-577000a726db.png)

**Comment by symroe** [comment]
My mistake – my adblocker was blocking that `div`. Sorry!

**Comment by symroe** [comment]
…and it seems like the count on the table I posted a screenshot of above is updated using javascript? And it wasn't able to count them, as my browser removed them from the DOM?

**Comment by andrew** [comment]
I think the count was cached into memcache a bit aggressively, I expired the cache when you first reported the issue
