### ISSUE TITLE
Add support for R / CRAN

### ISSUE THREAD

**Issue by cboettig** [librariesio/librarian-parsers#15]
It appears that libraries.io does not parse the dependencies on the R packages it indexes.  Looks like there should just a librarian parser for R packages to gather this data.

**Comment by andrew** [comment]
@cboettig do you know of any specification for parsing the DESCRIPTION files for cran?

**Comment by cboettig** [comment]
It's a Debian conf file format, so any tool that speaks that can parse them.  (Of course there are tools in R (mostly in the `utils` package) that will do this and offer some more fine-grained functionality to parsing certain fields)

**Comment by andrew** [comment]
@cboettig I've just added support to DESCRIPTION files, will take a little while to deploy and parse all the R projects dependencies now.

**Comment by cboettig** [comment]
@andrew Nice, thanks.  Really impressed by libraries.io. I haven't figured out quite how the different pieces are assembled -- looks like this parser is just getting dependencies from the Description file, and you are also already getting other metadata from GitHub (where applicable) and from CRAN index itself, or how these map on to whatever generic metadata model you are using behind the scenes as you aggregate over these different libraries.

I and others are working on a project that may have some relevance to you here, trying to come up with a more standard way to crosswalk between software metadata formats to facilitate tools like libraries.io.  It's still early stages for us but would definitely be interested in your input if something like this could be helpful for libraries.io: http://github.com/CodeMeta/codemeta

**Comment by andrew** [comment]
@cboettig this repo and https://github.com/librariesio/librarian are for pulling dependency information from github repo, the main repository https://github.com/librariesio/libraries.io pulls information from 32 different package managers (mapping code here: https://github.com/librariesio/libraries.io/tree/master/app/models/repositories), some of which pull down dependency information if provided in a parsable way by the package managers central repository.

Codemeta looks great, if you can get a good adoption from users/package managers then I can definitely use it for parsing information if available. 

I can also add support for generating a codemeta json/xml file for every projects/github repo index, similar to the support I have for ABOUT files: https://libraries.io/npm/chai.about
